### ISSUE TITLE
Failed to start service jboss.logging.handler.SYSLOG: 'x1.jboss.syslog.SyslogHandler' could not be found.

### ISSUE THREAD

**Issue by nandopires** [kifj/jboss-syslog#5]
Hello Johannes!

In my project, i'm using Jboss as 7.1.1.Final and jdk 1.6.0_33.

I have packaged with command mvn package at jdk 1.8.0_144 and installed as the instructions at README.md.

But, i've got the error message: Failed to start service jboss.logging.handler.SYSLOG: 'x1.jboss.syslog.SyslogHandler' could not be found.

So, after a few trying i could solve the problem changing the pom section wich defines the compiler target and source to 1.6. After this the problem is solved.

I think that register this information could save some hours for someone wich uses java 6.

**Comment by kifj** [comment]
Updated README
